export const demoConcepts = [
  {
    slug: "restaurant-cafe",
    title: "Atelier Moka",
    category: "Restaurant & café",
    description: "Une table de quartier chaleureuse, portée par une cuisine de saison et une atmosphère feutrée.",
    image: "/images/demos/restaurant-cafe/cover.svg",
    color: "#a94f35",
    tone: "Clair & éditorial",
  },
  {
    slug: "patisserie",
    title: "Maison Eclat",
    category: "Pâtisserie",
    description: "Une pâtisserie contemporaine aux couleurs délicates et aux créations très graphiques.",
    image: "/images/demos/patisserie/cover.svg",
    color: "#b7526e",
    tone: "Doux & précis",
  },
  {
    slug: "fast-food",
    title: "Smash District",
    category: "Fast-food",
    description: "Un comptoir urbain franc, généreux et rythmé, pensé pour donner faim dès le premier écran.",
    image: "/images/demos/fast-food/cover.svg",
    color: "#e54b22",
    tone: "Direct & vibrant",
  },
  {
    slug: "artisan",
    title: "Atelier Noroît",
    category: "Artisan",
    description: "Un univers tactile et rassurant qui valorise le geste, la matière et le travail bien fait.",
    image: "/images/demos/artisan/cover.svg",
    color: "#55705f",
    tone: "Brut & humain",
  },
  {
    slug: "consultant",
    title: "Élan Conseil",
    category: "Consultant",
    description: "Une présence claire et confiante pour présenter une expertise sans langage inutilement complexe.",
    image: "/images/demos/consultant/cover.svg",
    color: "#4358a6",
    tone: "Calme & assuré",
  },
  {
    slug: "pme-b2b",
    title: "Orbe Industrie",
    category: "PME B2B",
    description: "Une vitrine solide et technique qui rend une activité industrielle immédiatement compréhensible.",
    image: "/images/demos/pme-b2b/cover.svg",
    color: "#246d78",
    tone: "Fiable & structuré",
  },
  {
    slug: "dashboard",
    title: "Pilote",
    category: "Dashboard",
    description: "Une interface métier lisible où les données clés deviennent évidentes au premier regard.",
    image: "/images/demos/dashboard/cover.svg",
    color: "#6b56b3",
    tone: "Dense & fluide",
  },
  {
    slug: "landing",
    title: "Lumen",
    category: "Landing page",
    description: "Une page de lancement lumineuse, concise et rythmée autour d'une proposition forte.",
    image: "/images/demos/landing/cover.svg",
    color: "#ca7133",
    tone: "Net & expressif",
  },
];
