export const demoConcepts = [
  {
    slug: "atelier-moka",
    title: "Atelier Moka",
    category: "Restaurant & café",
    description: "Une table de quartier chaleureuse, portée par une cuisine de saison et une atmosphère feutrée.",
    image: "/images/demos/restaurant-cafe/cover.svg",
    color: "#a94f35",
    tone: "Clair & éditorial",
  },
  {
    slug: "maison-eclat",
    title: "Maison Eclat",
    category: "Pâtisserie",
    description: "Une pâtisserie contemporaine aux couleurs délicates et aux créations très graphiques.",
    image: "/images/demos/patisserie/cover.svg",
    color: "#b7526e",
    tone: "Doux & précis",
  },
  {
    slug: "smash-district",
    title: "Smash District",
    category: "Fast-food",
    description: "Un comptoir urbain franc, généreux et rythmé, pensé pour donner faim dès le premier écran.",
    image: "/images/demos/fast-food/cover.svg",
    color: "#e54b22",
    tone: "Direct & vibrant",
  },
  {
    slug: "atelier-noroit",
    title: "Atelier Noroît",
    category: "Artisan",
    description: "Un univers tactile et rassurant qui valorise le geste, la matière et le travail bien fait.",
    image: "/images/demos/artisan/cover.svg",
    color: "#55705f",
    tone: "Brut & humain",
  },
  {
    slug: "horizon-conseil",
    title: "Horizon Conseil",
    category: "Consultant",
    description: "Une présence claire et confiante pour structurer l’organisation et le pilotage des petites entreprises.",
    image: "/images/demos/consultant/cover.svg",
    color: "#153943",
    tone: "Clair & pragmatique",
  },
  {
    slug: "orbe-industrie",
    title: "Orbe Industrie",
    category: "PME B2B",
    description: "Une vitrine solide et technique qui rend une activité industrielle immédiatement compréhensible.",
    image: "/images/demos/pme-b2b/cover.svg",
    color: "#246d78",
    tone: "Fiable & structuré",
  },
  {
    slug: "pilote",
    title: "Pilote",
    category: "Dashboard",
    description: "Une interface métier lisible où les données clés deviennent évidentes au premier regard.",
    image: "/images/demos/dashboard/cover.svg",
    color: "#6b56b3",
    tone: "Dense & fluide",
  },
  {
    slug: "devisflow",
    title: "DevisFlow",
    category: "Landing page",
    description: "Un outil clair et direct pour créer, envoyer et suivre ses devis commerciaux.",
    image: "/images/demos/landing/cover.svg",
    color: "#3156f5",
    tone: "Direct & performant",
  },
];
