"use client";
import Image from "next/image";
import Link from "next/link";
import Reveal from "@/components/demos/shared/Reveal";

const base="/images/demos/artisan/";
const services=[["Rénovation complète","Appartement, maison ou local professionnel."],["Cuisine & salle de bain","Rénovation et remise aux normes."],["Peinture & finitions","Préparation, peinture et finitions intérieures."],["Aménagement","Cloisons, rangements et optimisation des espaces."]];
const projects=[["Appartement Bastille","Rénovation complète · 72 m²"],["Studio Montmartre","Optimisation & rénovation · 28 m²"],["Maison Vincennes","Pièces de vie · 95 m²"]];
const reviews=[["Laurent","Planning respecté, chantier propre et aucune surprise sur la facture."],["Sophie","Très bon suivi du début à la fin de notre rénovation."],["Mehdi","Un vrai confort d'avoir le même interlocuteur pendant tout le chantier."]];
const Button=({href,children,outline=false})=><a href={href} className={`inline-flex min-h-12 items-center justify-center px-6 text-sm font-bold transition hover:-translate-y-0.5 ${outline?"border border-[#12263d] text-[#12263d] hover:bg-[#12263d] hover:text-white":"bg-[#c78442] text-white hover:bg-[#a9672c]"}`}>{children}</a>;
const Heading=({label,children})=><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#a6652d]">{label}</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold leading-tight tracking-[-.045em] sm:text-6xl">{children}</h2></div>;

export default function ArtisanSite(){return <div className="bg-[#f7f4ed] text-[#12263d] selection:bg-[#c78442] selection:text-white">
  <header className="sticky top-0 z-40 border-b border-[#12263d]/10 bg-[#f7f4ed]/94 backdrop-blur-xl"><nav aria-label="Navigation principale" className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><a href="#accueil" className="text-xl font-bold tracking-[-.04em]">ATELIER <span className="text-[#c78442]">HABITAT</span></a><div className="hidden gap-8 text-sm font-semibold md:flex"><a href="#prestations">Prestations</a><a href="#realisations">Réalisations</a><a href="#process">Notre méthode</a></div><a href="#contact" className="bg-[#12263d] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#c78442]">Demander un devis</a></nav></header>
  <main>
    <section id="accueil" className="relative min-h-[82svh] overflow-hidden"><Image src={`${base}hero.jpg`} alt="Artisan étudiant les plans d'une rénovation" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#f7f4ed]/98 via-[#f7f4ed]/80 to-transparent"/><Reveal className="relative mx-auto flex min-h-[82svh] max-w-[1440px] items-center px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-2xl"><span className="inline-flex border border-[#c78442]/50 bg-white/50 px-4 py-2 text-xs font-bold uppercase tracking-[.14em]">Devis gratuit · Réponse sous 48 h</span><h1 className="mt-6 text-5xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-7xl lg:text-[5.8rem]">Vos travaux.<br/>Un seul interlocuteur.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#526171]">Rénovation intérieure, remise en état et aménagement sur mesure à Paris et proche couronne.</p><div className="mt-8 flex flex-wrap gap-3"><Button href="#contact">Demander un devis</Button><Button href="#realisations" outline>Voir nos réalisations</Button></div></div></Reveal></section>

    <section id="prestations" className="scroll-mt-20 px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-[1440px]"><Reveal><Heading label="Notre métier">Tout ce qu’il faut pour transformer votre intérieur.</Heading></Reveal><Reveal className="mt-12 grid border-l border-t border-[#12263d]/15 sm:grid-cols-2 lg:grid-cols-4" stagger={.08}>{services.map(([t,d],i)=><article key={t} data-reveal-item className="min-h-64 border-b border-r border-[#12263d]/15 p-6 transition hover:bg-white"><span className="text-sm font-bold text-[#c78442]">0{i+1}</span><h3 className="mt-14 text-2xl font-semibold">{t}</h3><p className="mt-3 text-sm leading-6 text-[#65717d]">{d}</p></article>)}</Reveal></div></section>

    <section className="bg-[#12263d] px-5 py-20 text-white sm:px-8 lg:px-10"><Reveal className="mx-auto max-w-[1440px]"><h2 className="text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Des travaux sans mauvaise surprise.</h2><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{["Devis détaillé","Planning clair","Un interlocuteur unique","Chantier suivi"].map((x,i)=><div key={x} data-reveal-item className="border-t border-white/25 pt-5"><span className="text-xs text-[#d8a56f]">0{i+1}</span><p className="mt-3 text-xl font-semibold">{x}</p></div>)}</div></Reveal></section>

    <section id="realisations" className="scroll-mt-20 px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-[1440px]"><Reveal><Heading label="Réalisations">Des espaces pensés pour durer.</Heading></Reveal><Reveal className="mt-12 space-y-14" stagger={.1}>{projects.map(([n,d],i)=><article key={n} data-reveal-item className={`grid gap-6 lg:grid-cols-[1.4fr_.6fr] lg:items-end ${i%2?"lg:grid-cols-[.6fr_1.4fr]":""}`}><div className={`relative min-h-[420px] overflow-hidden ${i%2?"lg:order-2":""}`}><Image src={`${base}project-${i+1}.jpg`} alt={n} fill sizes="70vw" className="object-cover transition duration-700 hover:scale-[1.025]"/></div><div className="border-t border-[#12263d]/20 pt-5"><span className="text-xs font-bold text-[#c78442]">PROJET 0{i+1}</span><h3 className="mt-3 text-3xl font-semibold">{n}</h3><p className="mt-3 text-[#65717d]">{d}</p></div></article>)}</Reveal></div></section>

    <section id="process" className="scroll-mt-20 bg-[#e5dfd2] px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-2"><Reveal><Heading label="Notre méthode">Votre projet en quatre étapes</Heading><div className="mt-12">{["Visite et échange","Devis détaillé","Réalisation","Réception du chantier"].map((x,i)=><div key={x} className="grid grid-cols-[3.5rem_1fr] items-center border-t border-[#12263d]/20 py-5"><span className="text-sm font-bold text-[#c78442]">0{i+1}</span><p className="text-xl font-semibold">{x}</p></div>)}</div></Reveal><Reveal className="grid grid-cols-2 gap-3"><div className="relative col-span-2 min-h-80"><Image src={`${base}craft.jpg`} alt="Artisan réalisant une finition intérieure" fill sizes="50vw" className="object-cover"/></div><div className="relative col-span-2 min-h-52 lg:col-span-1"><Image src={`${base}detail.jpg`} alt="Travail de finition précis" fill sizes="30vw" className="object-cover"/></div><div className="flex min-h-52 items-end bg-[#c78442] p-6 text-white"><p className="text-2xl font-semibold">Un geste précis.<br/>Un résultat durable.</p></div></Reveal></div></section>

    <section className="px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto max-w-[1440px]"><Reveal><Heading label="Ils nous ont fait confiance">Un chantier clair, du premier rendez-vous à la réception.</Heading></Reveal><Reveal className="mt-10 grid gap-5 lg:grid-cols-3" stagger={.1}>{reviews.map(([n,q])=><figure key={n} data-reveal-item className="border border-[#12263d]/15 bg-white p-7"><p className="text-[#c78442]">★★★★★</p><blockquote className="mt-6 text-xl leading-8">“{q}”</blockquote><figcaption className="mt-8 text-sm font-bold">{n}</figcaption></figure>)}</Reveal></div></section>

    <section className="bg-[#12263d] px-5 py-20 text-white sm:px-8 lg:px-10"><Reveal className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d8a56f]">Zone d’intervention</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Nous intervenons près de chez vous.</h2><p className="mt-5 text-white/60">Paris et proche couronne.</p></div><div className="grid grid-cols-2 gap-px bg-white/20">{["Paris","Boulogne-Billancourt","Vincennes","Montreuil","Levallois-Perret","Saint-Mandé"].map(x=><div key={x} className="bg-[#12263d] p-5 font-semibold">{x}</div>)}</div></Reveal></section>

    <section id="contact" className="scroll-mt-20 px-5 py-20 sm:px-8 sm:py-28 lg:px-10"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-[.75fr_1.25fr]"><Reveal><Heading label="Votre projet">Parlons de votre projet</Heading><p className="mt-6 leading-7 text-[#65717d]">Décrivez-nous votre besoin. Nous vous recontactons sous 48 heures pour organiser un premier échange.</p></Reveal><Reveal><form className="grid gap-5 sm:grid-cols-2" onSubmit={(e)=>e.preventDefault()}>{[["Nom","text"],["Email","email"],["Téléphone","tel"],["Type de projet","text"]].map(([l,t])=><label key={l} className="text-sm font-semibold">{l}<input type={t} className="mt-2 h-12 w-full border border-[#12263d]/25 bg-white px-4 focus:border-[#c78442] focus:outline-none"/></label>)}<label className="text-sm font-semibold sm:col-span-2">Message<textarea rows="5" className="mt-2 w-full border border-[#12263d]/25 bg-white p-4 focus:border-[#c78442] focus:outline-none"/></label><button type="submit" className="min-h-12 bg-[#c78442] px-6 font-bold text-white transition hover:bg-[#a9672c] sm:col-span-2 sm:justify-self-start">Recevoir une estimation</button></form></Reveal></div></section>
  </main><footer className="border-t border-[#12263d]/15 px-5 py-9 text-sm text-[#65717d] sm:px-8"><div className="mx-auto flex max-w-[1440px] flex-col gap-3 sm:flex-row sm:justify-between"><b className="text-[#12263d]">ATELIER HABITAT</b><span>Concept de démonstration · <Link href="/demo">Toutes les démos</Link></span></div></footer>
 </div>}
