"use client";
import Image from "next/image";
import Link from "next/link";
import Reveal from "@/components/demos/shared/Reveal";

const base = "/images/demos/fast-food/";
const burgers = [["District Original","Double smash, cheddar, pickles, sauce District","12,90 €"],["Hot One","Double smash, cheddar, jalapeños, sauce spicy","13,90 €"],["Chicken Crunch","Poulet croustillant, coleslaw, sauce maison","12,50 €"],["Veggie Melt","Galette végétale, cheddar, pickles, oignons","11,90 €"]];
const reviews = [["Alex","Enfin un burger simple, croustillant et vraiment généreux."],["Mélanie","Service rapide et le Hot One est incroyable."],["Sam","Les frites maison font clairement la différence."]];
const CTA = ({href,children,invert=false}) => <Link href={href} className={`inline-flex min-h-12 items-center justify-center border-2 border-[#ff4b20] px-6 text-sm font-black uppercase tracking-wide transition hover:-translate-y-1 ${invert ? "bg-[#ff4b20] text-black hover:bg-[#ff6a43]" : "text-[#ff4b20] hover:bg-[#ff4b20] hover:text-black"}`}>{children}</Link>;

export default function FastFoodSite(){return <div className="overflow-hidden bg-[#11110f] text-[#fff4de] selection:bg-[#ff4b20] selection:text-black">
  <header className="fixed inset-x-0 top-0 z-40 border-b-2 border-[#fff4de]/15 bg-[#11110f]/90 backdrop-blur-xl"><nav aria-label="Navigation principale" className="mx-auto flex h-16 max-w-[1320px] items-center justify-between px-5 sm:px-8 lg:px-10"><a href="#home" className="text-xl font-black italic tracking-[-.05em] sm:text-2xl">SMASH DISTRICT</a><div className="hidden gap-7 text-xs font-black uppercase md:flex"><a href="#burgers">Burgers</a><a href="#menus">Menus</a><a href="#local">Le shop</a></div><Link href="/demo/smash-district/commander" className="bg-[#ff4b20] px-4 py-2.5 text-xs font-black uppercase text-black transition hover:bg-white">Commander</Link></nav></header>
  <main>
    <section id="home" className="relative flex min-h-[680px] items-center pt-16 sm:min-h-[720px] lg:min-h-[760px]"><Image src={`${base}hero.jpg`} alt="Smash burger District Original" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black/95 via-black/55 to-transparent"/><Reveal className="relative mx-auto w-full max-w-[1320px] px-5 py-16 sm:px-8 lg:px-10"><div className="max-w-3xl"><span className="inline-block -rotate-2 bg-[#ff4b20] px-3 py-2 text-[.68rem] font-black uppercase tracking-[.16em] text-black">Préparé minute</span><h1 className="mt-5 text-[3.6rem] font-black uppercase italic leading-[.84] tracking-[-.07em] sm:text-[6rem] lg:text-[8rem]">Smashed hard.<br/><span className="text-[#ff4b20]">Served fast.</span></h1><p className="mt-6 max-w-lg text-base font-bold leading-7 sm:text-lg">Des smash burgers croustillants, des frites maison et aucune complication.</p><div className="mt-7 flex flex-wrap gap-3"><CTA href="#burgers" invert>Voir le menu</CTA><CTA href="/demo/smash-district/commander">Commander</CTA></div></div></Reveal></section>

    <section id="burgers" className="scroll-mt-16 bg-[#fff4de] px-5 py-16 text-[#11110f] sm:px-8 sm:py-20 lg:px-10"><div className="mx-auto max-w-[1320px]"><Reveal className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#e33f19]">Les incontournables</p><h2 className="mt-2 text-4xl font-black uppercase italic tracking-[-.055em] sm:text-6xl">Best sellers</h2></div><p className="border-2 border-black px-3 py-2 text-[.68rem] font-black uppercase">100% préparés minute</p></Reveal><Reveal className="mt-9 grid gap-4 sm:grid-cols-2" stagger={.08}>{burgers.map(([name,desc,price],i)=><article key={name} data-reveal-item className="group relative overflow-hidden border-2 border-black bg-[#e7d8bc]"><div className="relative aspect-[4/3]"><Image src={`${base}burger-${i+1}.jpg`} alt={name} fill sizes="(max-width: 640px) 100vw,50vw" className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="absolute inset-x-0 bottom-0 bg-[#11110f] p-4 text-[#fff4de] sm:p-5"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-black uppercase italic sm:text-2xl">{name}</h3><span className="bg-[#ff4b20] px-2 py-1 text-sm font-black text-black">{price}</span></div><p className="mt-2 text-xs text-white/65 sm:text-sm">{desc}</p></div></article>)}</Reveal></div></section>

    <div className="overflow-hidden border-y-2 border-black bg-[#ff4b20] py-3 text-black"><div className="flex w-max animate-[marquee_18s_linear_infinite] gap-8 whitespace-nowrap text-2xl font-black uppercase italic sm:text-4xl">{Array(4).fill("FRESH · SMASHED · CRISPY · FAST · ").map((x,i)=><span key={i}>{x}</span>)}</div></div>

    <section id="menus" className="scroll-mt-16 px-5 py-16 sm:px-8 sm:py-20 lg:px-10"><div className="mx-auto grid max-w-[1320px] gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Reveal><p className="text-xs font-black uppercase tracking-[.2em] text-[#ff4b20]">Choisis ton niveau</p><h2 className="mt-2 text-5xl font-black uppercase italic leading-[.9] tracking-[-.06em] sm:text-6xl">Les<br/>menus</h2><div className="relative mt-7 aspect-[16/10] overflow-hidden"><Image src={`${base}fries.jpg`} alt="Frites maison croustillantes" fill sizes="40vw" className="object-cover"/></div></Reveal><Reveal className="divide-y-2 divide-[#fff4de]/20 border-y-2 border-[#fff4de]/20">{[["Menu Solo","Burger + frites","15,90 €"],["Menu District","Burger + frites + boisson","18,50 €"],["Menu XL","Double burger + grande frite + boisson","21,90 €"]].map(([n,d,p],i)=><div key={n} className="group flex items-center gap-4 py-6"><span className="text-sm text-[#ff4b20]">0{i+1}</span><div className="flex-1"><h3 className="text-2xl font-black uppercase italic sm:text-3xl">{n}</h3><p className="mt-1 text-sm text-white/50">{d}</p></div><strong className="text-lg sm:text-xl">{p}</strong></div>)}</Reveal></div></section>

    <section className="bg-[#ff4b20] px-5 py-16 text-black sm:px-8 sm:py-20 lg:px-10"><Reveal className="mx-auto grid max-w-[1320px] gap-4 lg:grid-cols-3" stagger={.1}>{[["Smashé à la commande","Jamais préparé à l'avance."],["Frites maison","Croustillantes dehors, fondantes dedans."],["Click & collect","Tu commandes, on prépare, tu récupères."]].map(([t,d],i)=><div key={t} data-reveal-item className="border-2 border-black p-6"><span className="text-sm font-black">0{i+1}</span><h3 className="mt-8 text-2xl font-black uppercase italic">{t}</h3><p className="mt-2 text-sm font-semibold">{d}</p></div>)}</Reveal></section>

    <section className="px-5 py-16 sm:px-8 sm:py-20 lg:px-10"><div className="mx-auto max-w-[1320px]"><Reveal><h2 className="text-4xl font-black uppercase italic tracking-[-.05em] sm:text-6xl">Ils ont goûté.<br/><span className="text-[#ff4b20]">Ils ont parlé.</span></h2></Reveal><Reveal className="mt-8 grid gap-4 lg:grid-cols-3" stagger={.1}>{reviews.map(([n,q])=><figure key={n} data-reveal-item className="border-2 border-white/20 p-6"><p className="text-sm text-[#ff4b20]">★★★★★</p><blockquote className="mt-5 text-lg font-bold leading-7">“{q}”</blockquote><figcaption className="mt-6 text-xs font-black uppercase">— {n}</figcaption></figure>)}</Reveal></div></section>

    <section id="local" className="scroll-mt-16 grid lg:grid-cols-2"><div className="relative min-h-[400px] sm:min-h-[440px]"><Image src={`${base}interior.jpg`} alt="Burger shop SMASH DISTRICT" fill sizes="50vw" className="object-cover"/></div><Reveal className="flex items-center bg-[#fff4de] p-8 text-black sm:p-10"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#e33f19]">Paris 10e</p><h2 className="mt-3 text-4xl font-black uppercase italic tracking-[-.055em] sm:text-6xl">SMASH<br/>DISTRICT</h2><p className="mt-5 font-bold leading-7">42 rue du Passage, Paris 10e<br/><br/>Tous les jours<br/>11h30 — 23h</p><div className="mt-7"><CTA href="/demo/smash-district/commander" invert>Commander maintenant</CTA></div></div></Reveal></section>
  </main><footer className="flex flex-col gap-3 border-t-2 border-white/15 px-5 py-7 text-sm text-white/50 sm:flex-row sm:justify-between sm:px-8 lg:px-10"><b className="text-white">SMASH DISTRICT</b><span>Concept de démonstration · <Link href="/demo">Toutes les démos</Link></span></footer>
  <style jsx global>{`@keyframes marquee{to{transform:translateX(-25%)}}@media(prefers-reduced-motion:reduce){.animate-\[marquee_18s_linear_infinite\]{animation:none!important}}`}</style>
 </div>}
